name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build Jar
        run: kotlinc Main.kt -include-runtime -d MorseTranslator.jar

      - name: Publish Jar
        uses: actions/upload-artifact@v2
        with:
          name: MorseTranslator
          path: MorseTranslator.jar
